#!/usr/bin/expect
spawn mavproxy.py --logfile /tmp/mav.tlog  --auto-protocol --master udpout:192.168.0.100:14550
set timeout 350
expect_after eof {exit 0}
expect_after timeout {exit 1}
expect "Detected vehicle" { send "mode stabilize\r" }
expect "AP: ArduCopter" { send "wp load /home/user/ardupilot/demoMission.txt\r" }
expect "AP: Flight plan received" { send "wp loop\r" }
expect "Got MISSION_ACK: TYPE_MISSION: ACCEPTED" { send "arm throttle\r" }
expect "Got COMMAND_ACK: COMPONENT_ARM_DISARM: ACCEPTED" { send "arm throttle\r" }
expect "ARMED" { send "mode auto\r" }
expect "AP: Mission: 1 Takeoff" { send "long MAV_CMD_MISSION_START\r" }
expect "DISARMED" { exit }

